# Generated by Django 4.2.5 on 2023-09-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.listofcountries')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='accommodation_name')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='accommodation_img')),
                ('short_desc', models.TextField(blank=True, max_length=60, verbose_name='product Short Descr')),
                ('description', models.TextField(blank=True, verbose_name='Product Description')),
                ('availability', models.PositiveIntegerField(verbose_name='Qty of available rooms')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Room Price')),
                ('room_desc', models.TextField(blank=True, max_length=60, verbose_name='Room Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.listofcountries')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.regions')),
            ],
        ),
    ]
